### PR TITLE
feat(n4s): add isBlank rule

### PR DESCRIPTION
**Pull request by lpizzinidev**
Addresses #676

### CODE REVIEW

**Comment by ealush** [comment]
Hey @Pizzo15, thank you for this PR!

It makes great sense that Vest would come with this option, but this would be a major/breaking change and not a `patch` since it changes the way the library currently behaves.
Along with that, the current implementation is desired way, and I would much love to see your change appears in its own enforce rule, like so:

```
enforce("   ").isBlank(); // passes

enforce("   ").isNotBlank(); // throws
```

This should be easy enough to do.

Here are the general instructions:

1. Creating a new rule file:
Create a new file called "isBalnk.js" under [packages/n4s/src/rules](https://github.com/ealush/vest/tree/latest/packages/n4s/src/rules)

It should only cover strings, so the implementation should b quite simple as well.

2. Add a test file
Write the tests for the rule in the __tests__ directory.

3. Make enforce use the rule
Add the rule to the exported rules here: https://github.com/ealush/vest/blob/latest/packages/n4s/src/rules.js

4. Update the docs
Add usage example here: https://github.com/ealush/vest/blob/latest/packages/n4s/docs/rules.md


I am more than happy to help with any question you might have!

Thanks again

**Comment by lpizzinidev** [comment]
Hi @ealush, I've just implemented the `isBlank/isNotBlank` rule.
Let me know if there are any problems or changes to be made.
Thank you!

**Review by ealush — APPROVED** [review]
Awesome! Thank you for this change, @Pizzo15! Will be released soon.

**Comment by ealush** [comment]
Published in 3.2.6

**Pull request merged**
